## 산불 원인

![](https://www.forest.go.kr/kfsweb/cmm/fms/getImage.do?atchFileId=FILE_000000020058626&fileSn=1&thumbYn=)

## 계절별 비율

![](https://www.forest.go.kr/kfsweb/cmm/fms/getImage.do?atchFileId=FILE_000000020046889&fileSn=1&thumbYn=)

## 산불의 가장 큰 원인 
* 기후변화(습도, 풍속, 온도 등등)
* 등산객 수

In [1]:
import pandas as pd
import numpy as np

import requests
from bs4 import BeautifulSoup

In [2]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import time

f_day = '19800101'
l_day = '20101231'

endday = []
endmonth = []
endtime = []
endyear = []

firecause = []

locbunji = []
locsi = []
locdong = []
locgungu = []
locmenu = []

startday = []
startdayofweek = []
startmonth = []
starttime= []
startyear = []

damagearea= []


page = 1  # 1페이지에서만 데이터 받을 수 있음 

for p in range(1, page+1):

    key = 'lj1bcK6kk1SlfbI0bHFwZNqo8sjEyQJ0XDwGOjV70SP2vXBS/DosbER90s3y1LOZCPEcQn3SqArgHpIv+Azj1Q=='

    url = 'http://apis.data.go.kr/1400000/forestStusService/getfirestatsservice'

    params = {'serviceKey' : key, 'numOfRows' : '10000', 'pageNo' : page , 'searchStDt' : f_day, 'searchEdDt' : l_day }
    
    response = requests.get(url, params= params)
    time.sleep(0.3)
    res = response.text
    soup = BeautifulSoup(res,'html.parser')

    items = soup.find_all('item')
    for item in items:
        
        endday.append(item.find('endday'))
        endmonth.append(item.find('endmonth'))
        endtime.append(item.find('endtime'))
        endyear.append(item.find('endyear'))
        
        firecause.append(item.find('firecause'))
        
        locbunji.append(item.find('locbunji'))
        locdong.append(item.find('locdong'))
        locgungu.append(item.find('locgungu'))
        locmenu.append(item.find('locmenu'))
        locsi.append(item.find('locsi'))
        
        startday.append(item.find('startday'))
        startdayofweek.append(item.find('startdayofweek'))
        startmonth.append(item.find('startmonth'))
        starttime.append(item.find('starttime'))
        startyear.append(item.find('startyear'))
        
        damagearea.append(item.find('damagearea'))

        
df = pd.DataFrame({'startyear':startyear,'startmonth':startmonth,'startday':startday,'starttime':starttime,'startdayofweek':startdayofweek,
                   'endyear':endyear,'endmonth':endmonth,'endday':endday, 'endtime':endtime, 
                   'locbunji':locbunji,'locsi':locsi,'locgungu':locgungu,'locmenu':locmenu,'locdong': locdong,
                   'firecause':firecause, 'damagearea':damagearea
                 })

# df.to_csv('./data/산불_api.csv')

In [3]:
df

,startyear,startmonth,startday,starttime,startdayofweek,endyear,endmonth,endday,endtime,locbunji,locsi,locgungu,locmenu,locdong,firecause,damagearea
0,[2009],[11],[23],[14:20:00],[월요일],[2009],[11],[23],[15:30:00],[산78-1],[울산],[북],None,[연암동],[미정],[0.01]
1,[2009],[11],[24],[12:15:00],[화요일],[2009],[11],[24],[12:50:00],[산1-2],[경북],[봉화],[석포],[승부],[담배불실화],[0.1]
2,[2009],[11],[24],[14:25:00],[화요일],[2009],[11],[24],[14:50:00],[산103-1],[경북],[군위],[부계],[창평],[쓰레기소각],[0.1]
3,[2009],[12],[05],[19:26:00],[토요일],[2009],[12],[05],[21:50:00],[산51-100],[부산],[해운대],None,[반송],[입산자실화 추정],[0.12]
4,[2009],[12],[14],[15:25:00],[월요일],[2009],[12],[14],[16:35:00],[산7],[인천],[서],None,[석남동],[입산자실화],[0.5]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3390,[2006],[01],[02],[05:40:00],[월요일],[2006],[01],[02],[07:20:00],[산153],[경남],[마산],[구산],[내포],[입산자실화],[0.05]
3391,[2006],[01],[02],[15:31:00],[월요일],[2006],[01],[02],[15:50:00],[산198-2],[대구],[달서],[성당],None,[입산자실화],[0.02]
3392,[2006],[01],[03],[04:15:00],[화요일],[2006],[01],[03],[15:40:00],[산2-12],[경북],[칠곡],[지천],[심천],[입산자실화],[10]
3393,[2006],[01],[03],[05:40:00],[화요일],[2006],[01],[03],[09:10:00],[산6],[경북],[칠곡],[동명],[송산],[입산자실화],[3]
3394,[2006],[01],[03],[10:40:00],[화요일],[2006],[01],[03],[12:10:00],[산11],[경북],[영덕],[영해],[괴시],[입산자실화],[0.8]

In [5]:
# 데이터프레임 복제
df1 = df.copy()
df1

,startyear,startmonth,startday,starttime,startdayofweek,endyear,endmonth,endday,endtime,locbunji,locsi,locgungu,locmenu,locdong,firecause,damagearea
0,[2009],[11],[23],[14:20:00],[월요일],[2009],[11],[23],[15:30:00],[산78-1],[울산],[북],None,[연암동],[미정],[0.01]
1,[2009],[11],[24],[12:15:00],[화요일],[2009],[11],[24],[12:50:00],[산1-2],[경북],[봉화],[석포],[승부],[담배불실화],[0.1]
2,[2009],[11],[24],[14:25:00],[화요일],[2009],[11],[24],[14:50:00],[산103-1],[경북],[군위],[부계],[창평],[쓰레기소각],[0.1]
3,[2009],[12],[05],[19:26:00],[토요일],[2009],[12],[05],[21:50:00],[산51-100],[부산],[해운대],None,[반송],[입산자실화 추정],[0.12]
4,[2009],[12],[14],[15:25:00],[월요일],[2009],[12],[14],[16:35:00],[산7],[인천],[서],None,[석남동],[입산자실화],[0.5]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3390,[2006],[01],[02],[05:40:00],[월요일],[2006],[01],[02],[07:20:00],[산153],[경남],[마산],[구산],[내포],[입산자실화],[0.05]
3391,[2006],[01],[02],[15:31:00],[월요일],[2006],[01],[02],[15:50:00],[산198-2],[대구],[달서],[성당],None,[입산자실화],[0.02]
3392,[2006],[01],[03],[04:15:00],[화요일],[2006],[01],[03],[15:40:00],[산2-12],[경북],[칠곡],[지천],[심천],[입산자실화],[10]
3393,[2006],[01],[03],[05:40:00],[화요일],[2006],[01],[03],[09:10:00],[산6],[경북],[칠곡],[동명],[송산],[입산자실화],[3]
3394,[2006],[01],[03],[10:40:00],[화요일],[2006],[01],[03],[12:10:00],[산11],[경북],[영덕],[영해],[괴시],[입산자실화],[0.8]

In [6]:
for i in range(16):
    df1.iloc[:,i]=df.iloc[:,i].apply(lambda x: x.text if x else x )

In [7]:
df1

,startyear,startmonth,startday,starttime,startdayofweek,endyear,endmonth,endday,endtime,locbunji,locsi,locgungu,locmenu,locdong,firecause,damagearea
0,2009,11,23,14:20:00,월요일,2009,11,23,15:30:00,산78-1,울산,북,None,연암동,미정,0.01
1,2009,11,24,12:15:00,화요일,2009,11,24,12:50:00,산1-2,경북,봉화,석포,승부,담배불실화,0.1
2,2009,11,24,14:25:00,화요일,2009,11,24,14:50:00,산103-1,경북,군위,부계,창평,쓰레기소각,0.1
3,2009,12,05,19:26:00,토요일,2009,12,05,21:50:00,산51-100,부산,해운대,None,반송,입산자실화 추정,0.12
4,2009,12,14,15:25:00,월요일,2009,12,14,16:35:00,산7,인천,서,None,석남동,입산자실화,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3390,2006,01,02,05:40:00,월요일,2006,01,02,07:20:00,산153,경남,마산,구산,내포,입산자실화,0.05
3391,2006,01,02,15:31:00,월요일,2006,01,02,15:50:00,산198-2,대구,달서,성당,None,입산자실화,0.02
3392,2006,01,03,04:15:00,화요일,2006,01,03,15:40:00,산2-12,경북,칠곡,지천,심천,입산자실화,10
3393,2006,01,03,05:40:00,화요일,2006,01,03,09:10:00,산6,경북,칠곡,동명,송산,입산자실화,3
3394,2006,01,03,10:40:00,화요일,2006,01,03,12:10:00,산11,경북,영덕,영해,괴시,입산자실화,0.8

In [16]:
# df1.to_csv('./data/산불_api_수정.csv')