In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./data/기상청ASOS관측.csv',index_col=0)
df.head(3)

,지점 번호,관측지점,시간,평균 기온,최저 기온,최저 기온 시각,최고 기온,최대 기온 시각,10분 최다 강수량,10분 최다강수량 시각,...,0.5m 지중온도,1.0m 지중온도,1.5m 지중온도,3.0m 지중온도,5.0m 지중온도,합계 대형증발량,합계 소형증발량,9-9강수,일기현상,안개 계속 시간
0,105,강릉,1980-01-01,3.0,-0.4,714,7.0,1549.0,NaN,NaN,...,6.1,9.1,11.4,15.0,15.4,NaN,0.9,2.6,{비}2218-{비}{강도0}2400-,NaN
1,105,강릉,1980-01-02,6.0,3.5,207,8.4,1500.0,NaN,NaN,...,6.7,9.0,11.1,14.8,15.5,NaN,1.5,1.4,-{비}-{비}{강도0}0300-{비}{강도0}0600-{비}{강도0}0900-{비...,NaN
2,105,강릉,1980-01-03,7.5,4.1,1810,12.8,1330.0,NaN,NaN,...,6.8,9.0,11.0,14.8,15.3,NaN,2.2,NaN,NaN,NaN

In [51]:
df.shape

(176586, 62)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 176586 entries, 0 to 365
Data columns (total 62 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   지점 번호          176586 non-null  int64
 1   관측지점           176586 non-null  object
 2   시간             176586 non-null  object
 3   평균 기온          176581 non-null  float64
 4   최저 기온          176584 non-null  float64
 5   최저 기온 시각       176586 non-null  int64
 6   최고 기온          176583 non-null  float64
 7   최대 기온 시각       176584 non-null  float64
 8   10분 최다 강수량     44432 non-null   float64
 9   10분 최다강수량 시각   33429 non-null   float64
 10  1시간 최다강수량      44421 non-null   float64
 11  1시간 최다 강수량 시각  33543 non-null   float64
 12  sumRnDur       67858 non-null   float64
 13  일강수량           70401 non-null   float64
 14  최대 순간풍속        176561 non-null  float64
 15  최대 순간 풍속 풍향    176559 non-null  float64
 16  최대 순간풍속 시간     176561 non-null  float64
 17  최대 풍속          176571 non-null  float64
 18  최대 풍속 풍향       176571 non-null  float64
 19  최대 풍속 시각       176573 non-null  float64
 20  평균 풍속          176555 non-null  float64
 21  풍정합            176552 non-null  float64
 22  최대 풍향          176371 non-null  float64
 23  평균 이슬점온도       176581 non-null  float64
 24  최소 상대습도        176581 non-null  float64
 25  평균 상대습도 시각     176582 non-null  float64
 26  평균 상대습도        176577 non-null  float64
 27  평균 증기압         176576 non-null  float64
 28  평균 현지기압        176572 non-null  float64
 29  최고 해면 기압       176571 non-null  float64
 30  최고 해면기압 시각     176578 non-null  float64
 31  최저 해면기압        176567 non-null  float64
 32  최저 해면기압 시각     176577 non-null  float64
 33  평균 해면기압        176573 non-null  float64
 34  가조시간           176581 non-null  float64
 35  합계 일조 시간       176490 non-null  float64
 36  1시간 최다 일사량 시각  147010 non-null  float64
 37  1시간 최다 일사량     147012 non-null  float64
 38  합계 일사          152696 non-null  float64
 39  일 최심신적설        6938 non-null    float64
 40  일 최심신적설 시각     6586 non-null    float64
 41  일 최심적설         10878 non-null   float64
 42  일 최심적설 시각      10725 non-null   float64
 43  합계 3시간 신적설     6914 non-null    float64
 44  평균 전운량         170388 non-null  float64
 45  평균 중하층운량       169981 non-null  float64
 46  평균 지면온도        176567 non-null  float64
 47  최저 초상온도        176569 non-null  float64
 48  평균 5cm 지중온도    133896 non-null  float64
 49  평균10cm 지중온도    133852 non-null  float64
 50  평균 20cm 지중온도   133910 non-null  float64
 51  평균 30cm 지중온도   133899 non-null  float64
 52  0.5m 지중온도      133906 non-null  float64
 53  1.0m 지중온도      133910 non-null  float64
 54  1.5m 지중온도      109605 non-null  float64
 55  3.0m 지중온도      109603 non-null  float64
 56  5.0m 지중온도      109596 non-null  float64
 57  합계 대형증발량       96662 non-null   float64
 58  합계 소형증발량       142474 non-null  float64
 59  9-9강수          61584 non-null   float64
 60  일기현상           114903 non-null  object
 61  안개 계속 시간       11290 non-null   float64
dtypes: float64(57), int64(2), object(3)
memory usage: 84.9+ MB

In [4]:
# df.isnull().sum().sort_values(ascending =False)[:60]
# 비와 눈의 경우 안오면 nan값

In [5]:
# 전체 기후 feature
# '평균 기온', '최저 기온', '최저 기온 시각', '최고 기온',
# '최대 기온 시각', '10분 최다 강수량', '10분 최다강수량 시각', '1시간 최다강수량', '1시간 최다 강수량 시각','sumRnDur',
# '일강수량'
# '최대 순간풍속', '최대 순간 풍속 풍향', '최대 순간풍속 시간', '최대 풍속','최대 풍속 풍향', '최대 풍속 시각', '평균 풍속', 
# '풍정합', '최대 풍향'

# 평균 이슬점온도'

# '최소 상대습도','평균 상대습도 시각', '평균 상대습도'

# '평균 증기압', '평균 현지기압', '최고 해면 기압', '최고 해면기압 시각','최저 해면기압', '최저 해면기압 시각', '평균 해면기압'

#  '가조시간', '합계 일조 시간', '1시간 최다 일사량 시각','1시간 최다 일사량', '합계 일사'

#  '일 최심신적설', '일 최심신적설 시각', '일 최심적설', '일 최심적설 시각',

#  '합계 3시간 신적설', '평균 전운량', '평균 중하층운량', 

# '평균 지면온도', '최저 초상온도', 
# '평균 5cm 지중온도','평균10cm 지중온도', '평균 20cm 지중온도', '평균 30cm 지중온도', '0.5m 지중온도', '1.0m 지중온도',
# '1.5m 지중온도', '3.0m 지중온도', '5.0m 지중온도',

# '합계 대형증발량', '합계 소형증발량', '9-9강수',
# '일기현상', '안개 계속 시간'

In [6]:
# 사용할 feature

# '평균 기온',최저 기온','최고 기온',
# '일강수량',1시간 최다강수량'
# '최대 순간풍속', '최대 순간 풍속 풍향', '최대 풍속','최대 풍속 풍향'
# '평균 풍속'
# '풍정합', '최대 풍향'
# 평균 이슬점온도'
# '평균 상대습도'
# '평균 증기압',평균 현지기압','평균 해면기압','최고 해면 기압','최저 해면기압'
# '합계 일조 시간',합계 일사'
#  '일 최심신적설', '일 최심적설',
#  '평균 전운량','평균 중하층운량'
# '평균 지면온도', '평균 5cm 지중온도','평균10cm 지중온도',1시간 최다 일사량',
# '합계 대형증발량', '합계 소형증발량','안개 계속 시간'

# 제외한 feature
# 최저 기온 시각 최대 기온 시각', 
# '10분 최다 강수량', '10분 최다강수량 시각', '1시간 최다 강수량 시각','sumRnDur',
# '최대 순간풍속 시간', '최대 풍속 시각', 
# '최소 상대습도','평균 상대습도 시각'
# 최고 해면기압 시각', '최저 해면기압 시각'
# '가조시간','1시간 최다 일사량 시각','
# '일 최심신적설 시각','일 최심적설 시각'
# 
# '최저 초상온도', 
# '평균 20cm 지중온도', '평균 30cm 지중온도', '0.5m 지중온도', '1.0m 지중온도'
# '1.5m 지중온도', '3.0m 지중온도', '5.0m 지중온도'
# '9-9강수','일기현상',

In [8]:
df_c = pd.read_csv('./data/기상청ASOS관측.csv',\
                        usecols=['관측지점','시간','평균 기온','최저 기온','최고 기온',\
                                 '일강수량','1시간 최다강수량',\
                                 '최대 순간풍속','최대 순간 풍속 풍향', '최대 풍속','최대 풍속 풍향','평균 풍속','풍정합','최대 풍향',\
'평균 이슬점온도','평균 상대습도',\
'평균 증기압','평균 현지기압','평균 해면기압','최고 해면 기압','최저 해면기압',\
                                 '합계 일조 시간','합계 일사','1시간 최다 일사량',\
'일 최심신적설','일 최심적설','합계 3시간 신적설',\
                                 '평균 전운량','평균 중하층운량',\
'평균 지면온도', '평균 5cm 지중온도','평균10cm 지중온도',\
                                 '합계 대형증발량', '합계 소형증발량','안개 계속 시간'])

df_c.head()

,관측지점,시간,평균 기온,최저 기온,최고 기온,1시간 최다강수량,일강수량,최대 순간풍속,최대 순간 풍속 풍향,최대 풍속,...,일 최심적설,합계 3시간 신적설,평균 전운량,평균 중하층운량,평균 지면온도,평균 5cm 지중온도,평균10cm 지중온도,합계 대형증발량,합계 소형증발량,안개 계속 시간
0,강릉,1980-01-01,3.0,-0.4,7.0,NaN,0.4,6.4,200.0,3.3,...,1.3,1.4,9.5,-999.0,3.6,3.7,4.0,NaN,0.9,NaN
1,강릉,1980-01-02,6.0,3.5,8.4,NaN,3.6,4.1,180.0,2.3,...,NaN,NaN,10.0,-999.0,5.0,5.1,4.9,NaN,1.5,NaN
2,강릉,1980-01-03,7.5,4.1,12.8,NaN,NaN,10.0,230.0,5.3,...,NaN,NaN,9.0,-999.0,6.6,6.5,6.1,NaN,2.2,NaN
3,강릉,1980-01-04,4.1,-0.8,6.8,NaN,1.5,8.5,340.0,5.0,...,NaN,NaN,10.0,-999.0,4.3,5.5,5.9,NaN,1.8,NaN
4,강릉,1980-01-05,-0.8,-3.9,4.3,NaN,NaN,15.0,250.0,9.0,...,NaN,NaN,0.3,-999.0,0.8,1.6,3.2,NaN,2.0,NaN

In [52]:
df_c.shape

(176586, 35)

In [9]:
##  Nan값 처리하기

# 평온, 고온, 저온, 이슬점 - 보간
# 습도, 풍속, 해면기압 - 지역평균

In [10]:
df_c.columns

Index(['관측지점', '시간', '평균 기온', '최저 기온', '최고 기온', '1시간 최다강수량', '일강수량', '최대 순간풍속',
       '최대 순간 풍속 풍향', '최대 풍속', '최대 풍속 풍향', '평균 풍속', '풍정합', '최대 풍향', '평균 이슬점온도',
       '평균 상대습도', '평균 증기압', '평균 현지기압', '최고 해면 기압', '최저 해면기압', '평균 해면기압',
       '합계 일조 시간', '1시간 최다 일사량', '합계 일사', '일 최심신적설', '일 최심적설', '합계 3시간 신적설',
       '평균 전운량', '평균 중하층운량', '평균 지면온도', '평균 5cm 지중온도', '평균10cm 지중온도',
       '합계 대형증발량', '합계 소형증발량', '안개 계속 시간'],
      dtype='object')

In [11]:
df_seoul = df_c[(df_c['관측지점']== '서울')].sort_values(by='시간')

In [12]:
# Nan값 확인
df_seoul.isnull().sum().sort_values(ascending=False)

안개 계속 시간       14834
일 최심신적설        14759
합계 3시간 신적설     14757
일 최심적설         14260
1시간 최다강수량      11403
일강수량            9383
합계 대형증발량        6297
평균 5cm 지중온도     1470
평균10cm 지중온도     1470
합계 소형증발량        1467
1시간 최다 일사량       889
합계 일사             37
평균 중하층운량          21
합계 일조 시간          13
최대 풍향              6
풍정합                4
평균 풍속              4
최대 풍속 풍향           3
최대 풍속              3
최대 순간 풍속 풍향        3
최대 순간풍속            3
최저 해면기압            2
평균 지면온도            1
평균 현지기압            1
평균 해면기압            1
최고 해면 기압           1
최고 기온              1
시간                 0
평균 전운량             0
평균 증기압             0
평균 상대습도            0
평균 이슬점온도           0
최저 기온              0
평균 기온              0
관측지점               0
dtype: int64

In [14]:
# (1) 0값으로 채울 데이터 강수량, 적설량
lst_0 = ['1시간 최다강수량', '일강수량', '일 최심신적설', '일 최심적설', '합계 3시간 신적설','안개 계속 시간']
df_seoul[lst_0] = df_c[lst_0].fillna('0')
df_seoul[lst_0].isnull().sum()

1시간 최다강수량     0
일강수량          0
일 최심신적설       0
일 최심적설        0
합계 3시간 신적설    0
안개 계속 시간      0
dtype: int64

In [15]:
# (2)보간법 : 온도, 이슬점

columns1 =['평균 지면온도','최고 기온','평균 5cm 지중온도','평균10cm 지중온도']

df_seoul[columns1] = df_seoul[columns1].interpolate() 

df_seoul.isnull().sum()

관측지점              0
시간                0
평균 기온             0
최저 기온             0
최고 기온             0
1시간 최다강수량         0
일강수량              0
최대 순간풍속           3
최대 순간 풍속 풍향       3
최대 풍속             3
최대 풍속 풍향          3
평균 풍속             4
풍정합               4
최대 풍향             6
평균 이슬점온도          0
평균 상대습도           0
평균 증기압            0
평균 현지기압           1
최고 해면 기압          1
최저 해면기압           2
평균 해면기압           1
합계 일조 시간         13
1시간 최다 일사량      889
합계 일사            37
일 최심신적설           0
일 최심적설            0
합계 3시간 신적설        0
평균 전운량            0
평균 중하층운량         21
평균 지면온도           0
평균 5cm 지중온도       0
평균10cm 지중온도       0
합계 대형증발량       6297
합계 소형증발량       1467
안개 계속 시간          0
dtype: int64

In [17]:
# # 잘 들어갔는지 확인
# df_seoul.loc[158050:158095]

In [33]:
# 3개의 과정을 합친 코드

df_seoul = df_c[(df_c['관측지점']== '서울')].sort_values(by='시간')

# (1) 0값으로 채울 데이터 강수량, 적설량
lst_0 = ['1시간 최다강수량', '일강수량', '일 최심신적설', '일 최심적설', '합계 3시간 신적설','안개 계속 시간']
df_seoul[lst_0] = df_c[lst_0].fillna('0')
df_seoul[lst_0].isnull().sum()

# (2)보간법 : 온도, 이슬점

columns1 =['평균 지면온도','최고 기온','평균 5cm 지중온도','평균10cm 지중온도']

df_seoul[columns1] = df_seoul[columns1].interpolate() 

df_seoul.isnull().sum()

# (3) 평균값 :습도, 풍속, 해면기압 - 지역평균

columns2 = ['합계 대형증발량','합계 소형증발량','1시간 최다 일사량','합계 일사','평균 중하층운량','합계 일조 시간','최대 풍향',\
'평균 풍속','풍정합','최대 순간 풍속 풍향','최대 풍속 풍향','최대 풍속','최대 순간풍속','최저 해면기압','평균 현지기압',\
'평균 해면기압','최고 해면 기압']

df_seoul[columns2] = df_seoul[columns2].fillna(np.mean(df_seoul[columns2]))

df_seoul.isnull().sum()

관측지점           0
시간             0
평균 기온          0
최저 기온          0
최고 기온          0
1시간 최다강수량      0
일강수량           0
최대 순간풍속        0
최대 순간 풍속 풍향    0
최대 풍속          0
최대 풍속 풍향       0
평균 풍속          0
풍정합            0
최대 풍향          0
평균 이슬점온도       0
평균 상대습도        0
평균 증기압         0
평균 현지기압        0
최고 해면 기압       0
최저 해면기압        0
평균 해면기압        0
합계 일조 시간       0
1시간 최다 일사량     0
합계 일사          0
일 최심신적설        0
일 최심적설         0
합계 3시간 신적설     0
평균 전운량         0
평균 중하층운량       0
평균 지면온도        0
평균 5cm 지중온도    0
평균10cm 지중온도    0
합계 대형증발량       0
합계 소형증발량       0
안개 계속 시간       0
dtype: int64

In [ ]:
# 서울,경기도 : 서울
# 강원도 : 강릉, 춘천
# 충청남도 : 대전
# 충청북도 : 청주
# 전라북도 : 전주
# 전라남도 : 광주
# 경상북도 : 대구
# 경상남도 : 부산
# 제주도 : 제주

In [35]:
df['관측지점'].unique()

array(['강릉', '춘천', '울릉도', '광주', '대구', '대전', '부산', '서울', '전주', '제주', '청주',
       '백령도'], dtype=object)

In [38]:
# 서울

df_seoul = df_c[(df_c['관측지점']== '서울')].sort_values(by='시간')

# (1) 0값으로 채울 데이터 강수량, 적설량
lst_0 = ['1시간 최다강수량', '일강수량', '일 최심신적설', '일 최심적설', '합계 3시간 신적설','안개 계속 시간']
df_seoul[lst_0] = df_c[lst_0].fillna('0')
df_seoul[lst_0].isnull().sum()

# (2)보간법 : 온도, 이슬점

columns1 =['평균 지면온도','최고 기온','평균 5cm 지중온도','평균10cm 지중온도']

df_seoul[columns1] = df_seoul[columns1].interpolate() 

df_seoul.isnull().sum()

# (3) 평균값 :습도, 풍속, 해면기압 - 지역평균

columns2 = ['합계 대형증발량','합계 소형증발량','1시간 최다 일사량','합계 일사','평균 중하층운량','합계 일조 시간','최대 풍향',\
'평균 풍속','풍정합','최대 순간 풍속 풍향','최대 풍속 풍향','최대 풍속','최대 순간풍속','최저 해면기압','평균 현지기압',\
'평균 해면기압','최고 해면 기압']

df_seoul[columns2] = df_seoul[columns2].fillna(np.mean(df_seoul[columns2]))

df_seoul.isnull().sum()

관측지점           0
시간             0
평균 기온          0
최저 기온          0
최고 기온          0
1시간 최다강수량      0
일강수량           0
최대 순간풍속        0
최대 순간 풍속 풍향    0
최대 풍속          0
최대 풍속 풍향       0
평균 풍속          0
풍정합            0
최대 풍향          0
평균 이슬점온도       0
평균 상대습도        0
평균 증기압         0
평균 현지기압        0
최고 해면 기압       0
최저 해면기압        0
평균 해면기압        0
합계 일조 시간       0
1시간 최다 일사량     0
합계 일사          0
일 최심신적설        0
일 최심적설         0
합계 3시간 신적설     0
평균 전운량         0
평균 중하층운량       0
평균 지면온도        0
평균 5cm 지중온도    0
평균10cm 지중온도    0
합계 대형증발량       0
합계 소형증발량       0
안개 계속 시간       0
dtype: int64

In [39]:
# 강원도
df_gwd = df_c[(df_c['관측지점']== '춘천') | (df_c['관측지점']== '강릉')].sort_values(by='시간')

# (1) 0값으로 채울 데이터 강수량, 적설량
lst_0 = ['1시간 최다강수량', '일강수량', '일 최심신적설', '일 최심적설', '합계 3시간 신적설','안개 계속 시간']
df_gwd[lst_0] = df_c[lst_0].fillna('0')
df_gwd[lst_0].isnull().sum()

# (2)보간법 : 온도, 이슬점

columns1 =['평균 지면온도','최고 기온','평균 5cm 지중온도','평균10cm 지중온도','평균 이슬점온도','평균 기온']

df_gwd[columns1] = df_gwd[columns1].interpolate() 

# df_gwd.isnull().sum()

# (3) 평균값 :습도, 풍속, 해면기압 - 지역평균

columns2 = ['합계 대형증발량','합계 소형증발량','1시간 최다 일사량','합계 일사','평균 중하층운량','합계 일조 시간','최대 풍향',\
'평균 풍속','풍정합','최대 순간 풍속 풍향','최대 풍속 풍향','최대 풍속','최대 순간풍속','최저 해면기압','평균 현지기압',\
'평균 해면기압','최고 해면 기압','평균 증기압','평균 상대습도','평균 전운량']

df_gwd[columns2] = df_gwd[columns2].fillna(np.mean(df_gwd[columns2]))

df_gwd.isnull().sum()

관측지점           0
시간             0
평균 기온          0
최저 기온          0
최고 기온          0
1시간 최다강수량      0
일강수량           0
최대 순간풍속        0
최대 순간 풍속 풍향    0
최대 풍속          0
최대 풍속 풍향       0
평균 풍속          0
풍정합            0
최대 풍향          0
평균 이슬점온도       0
평균 상대습도        0
평균 증기압         0
평균 현지기압        0
최고 해면 기압       0
최저 해면기압        0
평균 해면기압        0
합계 일조 시간       0
1시간 최다 일사량     0
합계 일사          0
일 최심신적설        0
일 최심적설         0
합계 3시간 신적설     0
평균 전운량         0
평균 중하층운량       0
평균 지면온도        0
평균 5cm 지중온도    0
평균10cm 지중온도    0
합계 대형증발량       0
합계 소형증발량       0
안개 계속 시간       0
dtype: int64

In [40]:
# 충청남도 : 대전

df_cn = df_c[(df_c['관측지점']== '대전')].sort_values(by='시간')

# (1) 0값으로 채울 데이터 강수량, 적설량
lst_0 = ['1시간 최다강수량', '일강수량', '일 최심신적설', '일 최심적설', '합계 3시간 신적설','안개 계속 시간']
df_cn[lst_0] = df_c[lst_0].fillna('0')
df_cn[lst_0].isnull().sum()

# (2)보간법 : 온도, 이슬점

columns1 =['평균 지면온도','최고 기온','평균 5cm 지중온도','평균10cm 지중온도']

df_cn[columns1] = df_cn[columns1].interpolate() 

df_cn.isnull().sum()

# (3) 평균값 :습도, 풍속, 해면기압 - 지역평균

columns2 = ['합계 대형증발량','합계 소형증발량','1시간 최다 일사량','합계 일사','평균 중하층운량','합계 일조 시간','최대 풍향',\
'평균 풍속','풍정합','최대 순간 풍속 풍향','최대 풍속 풍향','최대 풍속','최대 순간풍속','최저 해면기압','평균 현지기압',\
'평균 해면기압','최고 해면 기압','평균 증기압','평균 상대습도','평균 전운량']

df_cn[columns2] = df_cn[columns2].fillna(np.mean(df_cn[columns2]))

df_cn.isnull().sum()

관측지점           0
시간             0
평균 기온          0
최저 기온          0
최고 기온          0
1시간 최다강수량      0
일강수량           0
최대 순간풍속        0
최대 순간 풍속 풍향    0
최대 풍속          0
최대 풍속 풍향       0
평균 풍속          0
풍정합            0
최대 풍향          0
평균 이슬점온도       0
평균 상대습도        0
평균 증기압         0
평균 현지기압        0
최고 해면 기압       0
최저 해면기압        0
평균 해면기압        0
합계 일조 시간       0
1시간 최다 일사량     0
합계 일사          0
일 최심신적설        0
일 최심적설         0
합계 3시간 신적설     0
평균 전운량         0
평균 중하층운량       0
평균 지면온도        0
평균 5cm 지중온도    0
평균10cm 지중온도    0
합계 대형증발량       0
합계 소형증발량       0
안개 계속 시간       0
dtype: int64

In [41]:
# 충청북도 : 청주

df_cb = df_c[(df_c['관측지점']== '청주')].sort_values(by='시간')

# (1) 0값으로 채울 데이터 강수량, 적설량
lst_0 = ['1시간 최다강수량', '일강수량', '일 최심신적설', '일 최심적설', '합계 3시간 신적설','안개 계속 시간']
df_cb[lst_0] = df_c[lst_0].fillna('0')
df_cb[lst_0].isnull().sum()

# (2)보간법 : 온도, 이슬점

columns1 =['평균 지면온도','최고 기온','평균 5cm 지중온도','평균10cm 지중온도']

df_cb[columns1] = df_cb[columns1].interpolate() 

df_cb.isnull().sum()

# (3) 평균값 :습도, 풍속, 해면기압 - 지역평균

columns2 = ['합계 대형증발량','합계 소형증발량','1시간 최다 일사량','합계 일사','평균 중하층운량','합계 일조 시간','최대 풍향',\
'평균 풍속','풍정합','최대 순간 풍속 풍향','최대 풍속 풍향','최대 풍속','최대 순간풍속','최저 해면기압','평균 현지기압',\
'평균 해면기압','최고 해면 기압']

df_cb[columns2] = df_cb[columns2].fillna(np.mean(df_cb[columns2]))

df_cb.isnull().sum()

관측지점           0
시간             0
평균 기온          0
최저 기온          0
최고 기온          0
1시간 최다강수량      0
일강수량           0
최대 순간풍속        0
최대 순간 풍속 풍향    0
최대 풍속          0
최대 풍속 풍향       0
평균 풍속          0
풍정합            0
최대 풍향          0
평균 이슬점온도       0
평균 상대습도        0
평균 증기압         0
평균 현지기압        0
최고 해면 기압       0
최저 해면기압        0
평균 해면기압        0
합계 일조 시간       0
1시간 최다 일사량     0
합계 일사          0
일 최심신적설        0
일 최심적설         0
합계 3시간 신적설     0
평균 전운량         0
평균 중하층운량       0
평균 지면온도        0
평균 5cm 지중온도    0
평균10cm 지중온도    0
합계 대형증발량       0
합계 소형증발량       0
안개 계속 시간       0
dtype: int64

In [42]:
# 전라북도 : 전주

df_jb = df_c[(df_c['관측지점']== '전주')].sort_values(by='시간')

# (1) 0값으로 채울 데이터 강수량, 적설량
lst_0 = ['1시간 최다강수량', '일강수량', '일 최심신적설', '일 최심적설', '합계 3시간 신적설','안개 계속 시간']
df_jb[lst_0] = df_c[lst_0].fillna('0')
df_jb[lst_0].isnull().sum()

# (2)보간법 : 온도, 이슬점

columns1 =['평균 지면온도','최고 기온','평균 5cm 지중온도','평균10cm 지중온도','최저 기온']

df_jb[columns1] = df_jb[columns1].interpolate() 

df_jb.isnull().sum()

# (3) 평균값 :습도, 풍속, 해면기압 - 지역평균

columns2 = ['합계 대형증발량','합계 소형증발량','1시간 최다 일사량','합계 일사','평균 중하층운량','합계 일조 시간','최대 풍향',\
'평균 풍속','풍정합','최대 순간 풍속 풍향','최대 풍속 풍향','최대 풍속','최대 순간풍속','최저 해면기압','평균 현지기압',\
'평균 해면기압','최고 해면 기압']

df_jb[columns2] = df_jb[columns2].fillna(np.mean(df_jb[columns2]))

df_jb.isnull().sum()

관측지점           0
시간             0
평균 기온          0
최저 기온          0
최고 기온          0
1시간 최다강수량      0
일강수량           0
최대 순간풍속        0
최대 순간 풍속 풍향    0
최대 풍속          0
최대 풍속 풍향       0
평균 풍속          0
풍정합            0
최대 풍향          0
평균 이슬점온도       0
평균 상대습도        0
평균 증기압         0
평균 현지기압        0
최고 해면 기압       0
최저 해면기압        0
평균 해면기압        0
합계 일조 시간       0
1시간 최다 일사량     0
합계 일사          0
일 최심신적설        0
일 최심적설         0
합계 3시간 신적설     0
평균 전운량         0
평균 중하층운량       0
평균 지면온도        0
평균 5cm 지중온도    0
평균10cm 지중온도    0
합계 대형증발량       0
합계 소형증발량       0
안개 계속 시간       0
dtype: int64

In [43]:
# 전라남도 : 광주

df_jn = df_c[(df_c['관측지점']== '광주')].sort_values(by='시간')

# (1) 0값으로 채울 데이터 강수량, 적설량
lst_0 = ['1시간 최다강수량', '일강수량', '일 최심신적설', '일 최심적설', '합계 3시간 신적설','안개 계속 시간']
df_jn[lst_0] = df_c[lst_0].fillna('0')
df_jn[lst_0].isnull().sum()

# (2)보간법 : 온도, 이슬점

columns1 =['평균 지면온도','최고 기온','평균 5cm 지중온도','평균10cm 지중온도']

df_jn[columns1] = df_jn[columns1].interpolate() 

df_jn.isnull().sum()

# (3) 평균값 :습도, 풍속, 해면기압 - 지역평균

columns2 = ['합계 대형증발량','합계 소형증발량','1시간 최다 일사량','합계 일사','평균 중하층운량','합계 일조 시간','최대 풍향',\
'평균 풍속','풍정합','최대 순간 풍속 풍향','최대 풍속 풍향','최대 풍속','최대 순간풍속','최저 해면기압','평균 현지기압',\
'평균 해면기압','최고 해면 기압']

df_jn[columns2] = df_jn[columns2].fillna(np.mean(df_jn[columns2]))

df_jn.isnull().sum()

관측지점           0
시간             0
평균 기온          0
최저 기온          0
최고 기온          0
1시간 최다강수량      0
일강수량           0
최대 순간풍속        0
최대 순간 풍속 풍향    0
최대 풍속          0
최대 풍속 풍향       0
평균 풍속          0
풍정합            0
최대 풍향          0
평균 이슬점온도       0
평균 상대습도        0
평균 증기압         0
평균 현지기압        0
최고 해면 기압       0
최저 해면기압        0
평균 해면기압        0
합계 일조 시간       0
1시간 최다 일사량     0
합계 일사          0
일 최심신적설        0
일 최심적설         0
합계 3시간 신적설     0
평균 전운량         0
평균 중하층운량       0
평균 지면온도        0
평균 5cm 지중온도    0
평균10cm 지중온도    0
합계 대형증발량       0
합계 소형증발량       0
안개 계속 시간       0
dtype: int64

In [44]:
# 경상북도 : 대구

df_kb = df_c[(df_c['관측지점']== '대구')].sort_values(by='시간')

# (1) 0값으로 채울 데이터 강수량, 적설량
lst_0 = ['1시간 최다강수량', '일강수량', '일 최심신적설', '일 최심적설', '합계 3시간 신적설','안개 계속 시간']
df_kb[lst_0] = df_c[lst_0].fillna('0')
df_kb[lst_0].isnull().sum()

# (2)보간법 : 온도, 이슬점

columns1 =['평균 지면온도','최고 기온','평균 5cm 지중온도','평균10cm 지중온도','평균 기온','평균 이슬점온도']

df_kb[columns1] = df_kb[columns1].interpolate() 

df_kb.isnull().sum()

# (3) 평균값 :습도, 풍속, 해면기압 - 지역평균

columns2 = ['합계 대형증발량','합계 소형증발량','1시간 최다 일사량','합계 일사','평균 중하층운량','합계 일조 시간','최대 풍향',\
'평균 풍속','풍정합','최대 순간 풍속 풍향','최대 풍속 풍향','최대 풍속','최대 순간풍속','최저 해면기압','평균 현지기압',\
'평균 해면기압','최고 해면 기압','평균 전운량','평균 상대습도','평균 증기압']

df_kb[columns2] = df_kb[columns2].fillna(np.mean(df_kb[columns2]))

df_kb.isnull().sum()

관측지점           0
시간             0
평균 기온          0
최저 기온          0
최고 기온          0
1시간 최다강수량      0
일강수량           0
최대 순간풍속        0
최대 순간 풍속 풍향    0
최대 풍속          0
최대 풍속 풍향       0
평균 풍속          0
풍정합            0
최대 풍향          0
평균 이슬점온도       0
평균 상대습도        0
평균 증기압         0
평균 현지기압        0
최고 해면 기압       0
최저 해면기압        0
평균 해면기압        0
합계 일조 시간       0
1시간 최다 일사량     0
합계 일사          0
일 최심신적설        0
일 최심적설         0
합계 3시간 신적설     0
평균 전운량         0
평균 중하층운량       0
평균 지면온도        0
평균 5cm 지중온도    0
평균10cm 지중온도    0
합계 대형증발량       0
합계 소형증발량       0
안개 계속 시간       0
dtype: int64

In [45]:
# 경상남도 : 부산

df_kn = df_c[(df_c['관측지점']== '대전')].sort_values(by='시간')

# (1) 0값으로 채울 데이터 강수량, 적설량
lst_0 = ['1시간 최다강수량', '일강수량', '일 최심신적설', '일 최심적설', '합계 3시간 신적설','안개 계속 시간']
df_kn[lst_0] = df_c[lst_0].fillna('0')
df_kn[lst_0].isnull().sum()

# (2)보간법 : 온도, 이슬점

columns1 =['평균 지면온도','최고 기온','평균 5cm 지중온도','평균10cm 지중온도']

df_kn[columns1] = df_kn[columns1].interpolate() 

df_kn.isnull().sum()

# (3) 평균값 :습도, 풍속, 해면기압 - 지역평균

columns2 = ['합계 대형증발량','합계 소형증발량','1시간 최다 일사량','합계 일사','평균 중하층운량','합계 일조 시간','최대 풍향',\
'평균 풍속','풍정합','최대 순간 풍속 풍향','최대 풍속 풍향','최대 풍속','최대 순간풍속','최저 해면기압','평균 현지기압',\
'평균 해면기압','최고 해면 기압','평균 전운량','평균 상대습도','평균 증기압']

df_kn[columns2] = df_kn[columns2].fillna(np.mean(df_kn[columns2]))

df_kn.isnull().sum()

관측지점           0
시간             0
평균 기온          0
최저 기온          0
최고 기온          0
1시간 최다강수량      0
일강수량           0
최대 순간풍속        0
최대 순간 풍속 풍향    0
최대 풍속          0
최대 풍속 풍향       0
평균 풍속          0
풍정합            0
최대 풍향          0
평균 이슬점온도       0
평균 상대습도        0
평균 증기압         0
평균 현지기압        0
최고 해면 기압       0
최저 해면기압        0
평균 해면기압        0
합계 일조 시간       0
1시간 최다 일사량     0
합계 일사          0
일 최심신적설        0
일 최심적설         0
합계 3시간 신적설     0
평균 전운량         0
평균 중하층운량       0
평균 지면온도        0
평균 5cm 지중온도    0
평균10cm 지중온도    0
합계 대형증발량       0
합계 소형증발량       0
안개 계속 시간       0
dtype: int64

In [65]:
# 제주도 : 제주

df_jj = df_c[(df_c['관측지점']== '제주')].sort_values(by='시간')

# (1) 0값으로 채울 데이터 강수량, 적설량
lst_0 = ['1시간 최다강수량', '일강수량', '일 최심신적설', '일 최심적설', '합계 3시간 신적설','안개 계속 시간']
df_jj[lst_0] = df_c[lst_0].fillna('0')
df_jj[lst_0].isnull().sum()

# (2)보간법 : 온도, 이슬점

columns1 =['평균 지면온도','최고 기온','평균 5cm 지중온도','평균10cm 지중온도']

df_jj[columns1] = df_jj[columns1].interpolate() 

df_jj.isnull().sum()

# (3) 평균값 :습도, 풍속, 해면기압 - 지역평균

columns2 = ['합계 대형증발량','합계 소형증발량','1시간 최다 일사량','합계 일사','평균 중하층운량','합계 일조 시간','최대 풍향',\
'평균 풍속','풍정합','최대 순간 풍속 풍향','최대 풍속 풍향','최대 풍속','최대 순간풍속','최저 해면기압','평균 현지기압',\
'평균 해면기압','최고 해면 기압','평균 전운량','평균 상대습도','평균 증기압']

df_jj[columns2] = df_jj[columns2].fillna(np.mean(df_jj[columns2]))

df_jj.isnull().sum()

관측지점           0
시간             0
평균 기온          0
최저 기온          0
최고 기온          0
1시간 최다강수량      0
일강수량           0
최대 순간풍속        0
최대 순간 풍속 풍향    0
최대 풍속          0
최대 풍속 풍향       0
평균 풍속          0
풍정합            0
최대 풍향          0
평균 이슬점온도       0
평균 상대습도        0
평균 증기압         0
평균 현지기압        0
최고 해면 기압       0
최저 해면기압        0
평균 해면기압        0
합계 일조 시간       0
1시간 최다 일사량     0
합계 일사          0
일 최심신적설        0
일 최심적설         0
합계 3시간 신적설     0
평균 전운량         0
평균 중하층운량       0
평균 지면온도        0
평균 5cm 지중온도    0
평균10cm 지중온도    0
합계 대형증발량       0
합계 소형증발량       0
안개 계속 시간       0
dtype: int64

In [55]:
# 울릉도

df_ul = df_c[(df_c['관측지점']== '울릉도')].sort_values(by='시간')

# (1) 0값으로 채울 데이터 강수량, 적설량
lst_0 = ['1시간 최다강수량', '일강수량', '일 최심신적설', '일 최심적설', '합계 3시간 신적설','안개 계속 시간']
df_ul[lst_0] = df_c[lst_0].fillna('0')
df_ul[lst_0].isnull().sum()

# (2)보간법 : 온도, 이슬점

columns1 =['평균 지면온도','최고 기온','평균 5cm 지중온도','평균10cm 지중온도','평균 기온','최저 기온']

df_ul[columns1] = df_ul[columns1].interpolate() 

df_ul.isnull().sum()

# (3) 평균값 :습도, 풍속, 해면기압 - 지역평균

columns2 = ['합계 대형증발량','합계 소형증발량','1시간 최다 일사량','합계 일사','평균 중하층운량','합계 일조 시간','최대 풍향',\
'평균 풍속','풍정합','최대 순간 풍속 풍향','최대 풍속 풍향','최대 풍속','최대 순간풍속','최저 해면기압','평균 현지기압',\
'평균 해면기압','최고 해면 기압','평균 전운량','평균 상대습도','평균 증기압']

df_ul[columns2] = df_ul[columns2].fillna(np.mean(df_ul[columns2]))

df_ul.isnull().sum()

관측지점           0
시간             0
평균 기온          0
최저 기온          0
최고 기온          0
1시간 최다강수량      0
일강수량           0
최대 순간풍속        0
최대 순간 풍속 풍향    0
최대 풍속          0
최대 풍속 풍향       0
평균 풍속          0
풍정합            0
최대 풍향          0
평균 이슬점온도       0
평균 상대습도        0
평균 증기압         0
평균 현지기압        0
최고 해면 기압       0
최저 해면기압        0
평균 해면기압        0
합계 일조 시간       0
1시간 최다 일사량     0
합계 일사          0
일 최심신적설        0
일 최심적설         0
합계 3시간 신적설     0
평균 전운량         0
평균 중하층운량       0
평균 지면온도        0
평균 5cm 지중온도    0
평균10cm 지중온도    0
합계 대형증발량       0
합계 소형증발량       0
안개 계속 시간       0
dtype: int64

In [57]:
# 백령도

df_baek = df_c[(df_c['관측지점']== '백령도')].sort_values(by='시간')

# (1) 0값으로 채울 데이터 강수량, 적설량
lst_0 = ['1시간 최다강수량', '일강수량', '일 최심신적설', '일 최심적설', '합계 3시간 신적설','안개 계속 시간']
df_baek[lst_0] = df_c[lst_0].fillna('0')
df_baek[lst_0].isnull().sum()

df_baek['평균 5cm 지중온도','평균10cm 지중온도']

# (2)보간법 : 온도, 이슬점

columns1 =['평균 지면온도','최고 기온','평균 5cm 지중온도','평균10cm 지중온도','평균 이슬점온도']

df_baek[columns1] = df_baek[columns1].interpolate() 

df_baek.isnull().sum()

# (3) 평균값 :습도, 풍속, 해면기압 - 지역평균

columns2 = ['합계 대형증발량','합계 소형증발량','1시간 최다 일사량','합계 일사','평균 중하층운량','합계 일조 시간','최대 풍향',\
'평균 풍속','풍정합','최대 순간 풍속 풍향','최대 풍속 풍향','최대 풍속','최대 순간풍속','최저 해면기압','평균 현지기압',\
'평균 해면기압','최고 해면 기압','평균 전운량','평균 상대습도','평균 증기압']

df_baek[columns2] = df_baek[columns2].fillna(np.mean(df_baek[columns2]))

df_baek.isnull().sum()

관측지점              0
시간                0
평균 기온             0
최저 기온             0
최고 기온             0
1시간 최다강수량         0
일강수량              0
최대 순간풍속           0
최대 순간 풍속 풍향       0
최대 풍속             0
최대 풍속 풍향          0
평균 풍속             0
풍정합               0
최대 풍향             0
평균 이슬점온도          0
평균 상대습도           0
평균 증기압            0
평균 현지기압           0
최고 해면 기압          0
최저 해면기압           0
평균 해면기압           0
합계 일조 시간          0
1시간 최다 일사량        0
합계 일사             0
일 최심신적설           0
일 최심적설            0
합계 3시간 신적설        0
평균 전운량            0
평균 중하층운량          0
평균 지면온도           0
평균 5cm 지중온도    7824
평균10cm 지중온도    7824
합계 대형증발량          0
합계 소형증발량          0
안개 계속 시간          0
dtype: int64

In [61]:
df_baek['평균 5cm 지중온도'].unique()

array([nan])

In [47]:
# 서울,경기도 : 서울
# 강원도 : 강릉, 춘천
# 충청남도 : 대전
# 충청북도 : 청주
# 전라북도 : 전주
# 전라남도 : 광주
# 경상북도 : 대구
# 경상남도 : 부산
# 8개

# 제주도 : 제주
# 울릉도,백령도

In [66]:
df_land_c = pd.concat([df_seoul,df_gwd,df_cn,df_cb,df_jb,df_jn,df_kb,df_kn])
df_land_c

,관측지점,시간,평균 기온,최저 기온,최고 기온,1시간 최다강수량,일강수량,최대 순간풍속,최대 순간 풍속 풍향,최대 풍속,...,일 최심적설,합계 3시간 신적설,평균 전운량,평균 중하층운량,평균 지면온도,평균 5cm 지중온도,평균10cm 지중온도,합계 대형증발량,합계 소형증발량,안개 계속 시간
2569,서울,1980-01-01,3.8,0.5,6.6,0,0.0,6.7,20.0,4.0,...,0,0,8.0,-999.0,0.2,-0.4,0.5,2.721902,1.8,0
2570,서울,1980-01-02,4.7,3.5,5.9,0,9.9,9.9,20.0,4.7,...,0,0,10.0,-999.0,1.9,1.3,0.5,2.721902,0.8,0
2571,서울,1980-01-03,3.8,-0.5,6.2,0,0,8.9,270.0,7.2,...,0,0,9.5,-999.0,2.8,2.8,2.3,2.721902,0.9,0
2572,서울,1980-01-04,-3.2,-6.9,-0.5,0,0,9.8,270.0,6.0,...,0,0,4.3,-999.0,-1.0,-0.5,1.0,2.721902,1.5,0
2573,서울,1980-01-05,-5.3,-9.1,-1.0,0,0.6,6.2,230.0,5.7,...,1.2,0.0,2.5,-999.0,-2.5,-2.4,0.0,2.721902,2.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174391,대전,2021-12-28,-0.5,-3.2,3.5,0,0.0,2.5,340.0,1.7,...,0,0,6.5,6.5,-1.1,-0.5,0.0,0.500000,0.7,0
174392,대전,2021-12-29,2.4,-2.1,7.2,0,0.0,11.3,340.0,5.2,...,0,0,6.5,5.9,0.5,-0.4,0.2,1.000000,1.5,0
174393,대전,2021-12-30,-1.4,-4.5,3.0,0,0.5,10.6,340.0,4.8,...,2.3,2.5,5.5,4.4,-0.7,-0.2,0.5,0.900000,1.4,0
174394,대전,2021-12-31,-5.0,-8.3,0.5,0,0.0,10.2,340.0,5.9,...,2.0,0,0.0,0.0,-2.0,-0.1,0.6,1.300000,1.9,0
174395,대전,2022-01-01,-4.4,-10.0,2.3,0,0,4.7,20.0,2.8,...,0,0,2.9,1.1,-3.4,-0.7,0.2,1.100000,1.6,0

In [67]:
df_land_c.isnull().sum()

관측지점           0
시간             0
평균 기온          0
최저 기온          0
최고 기온          0
1시간 최다강수량      0
일강수량           0
최대 순간풍속        0
최대 순간 풍속 풍향    0
최대 풍속          0
최대 풍속 풍향       0
평균 풍속          0
풍정합            0
최대 풍향          0
평균 이슬점온도       0
평균 상대습도        0
평균 증기압         0
평균 현지기압        0
최고 해면 기압       0
최저 해면기압        0
평균 해면기압        0
합계 일조 시간       0
1시간 최다 일사량     0
합계 일사          0
일 최심신적설        0
일 최심적설         0
합계 3시간 신적설     0
평균 전운량         0
평균 중하층운량       0
평균 지면온도        0
평균 5cm 지중온도    0
평균10cm 지중온도    0
합계 대형증발량       0
합계 소형증발량       0
안개 계속 시간       0
dtype: int64

In [72]:
df_sea_c = pd.concat([df_jj,df_ul,df_baek])
df_sea_c

,관측지점,시간,평균 기온,최저 기온,최고 기온,1시간 최다강수량,일강수량,최대 순간풍속,최대 순간 풍속 풍향,최대 풍속,...,일 최심적설,합계 3시간 신적설,평균 전운량,평균 중하층운량,평균 지면온도,평균 5cm 지중온도,평균10cm 지중온도,합계 대형증발량,합계 소형증발량,안개 계속 시간
3303,제주,1980-01-01,11.9,8.8,13.3,0,3.5,12.5,90.0,7.5,...,0,0,10.0,-999.0,10.7,10.3,9.7,2.614596,1.5,0
3304,제주,1980-01-02,14.1,12.7,15.3,0,0.4,11.4,110.0,8.7,...,0,0,10.0,-999.0,12.4,12.2,11.3,2.614596,1.0,0
3305,제주,1980-01-03,10.1,7.2,13.2,0,1.2,11.5,340.0,8.3,...,0,0,10.0,-999.0,9.1,10.1,10.5,2.614596,0.8,0
3306,제주,1980-01-04,6.2,3.4,7.7,0,0.1,20.5,340.0,12.7,...,0,0,9.8,-999.0,4.7,6.1,7.1,2.614596,2.7,0
3307,제주,1980-01-05,3.9,2.6,4.8,0,0.0,19.6,340.0,13.3,...,0,0,10.0,-999.0,2.8,4.2,5.0,2.614596,1.5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175486,백령도,2021-12-28,2.0,-1.4,5.8,0,0.0,9.5,140.0,7.2,...,0.8,0.0,5.3,4.5,-2.1,NaN,NaN,1.100000,1.5,0
175487,백령도,2021-12-29,2.7,-1.7,6.5,0,0,19.8,340.0,13.3,...,0,0,5.3,5.3,1.3,NaN,NaN,2.000000,2.8,0
175488,백령도,2021-12-30,-0.8,-2.2,1.4,0,0.3,21.1,340.0,14.2,...,0,0.0,6.1,6.1,-1.2,NaN,NaN,1.800000,2.5,0
175489,백령도,2021-12-31,-3.1,-3.9,-1.5,0,0.0,20.6,340.0,13.4,...,0,0,4.8,4.8,-2.7,NaN,NaN,1.100000,1.6,0
175490,백령도,2022-01-01,2.1,-4.2,6.7,0,0.7,11.5,270.0,7.6,...,0,0,8.4,6.8,-0.6,NaN,NaN,1.200000,1.7,0

In [73]:
df_sea_c.drop(columns = ['평균 5cm 지중온도','평균10cm 지중온도'], inplace=True)

In [74]:
df_sea_c.isnull().sum().sum()

0

In [76]:
# df_land_c.to_csv('./data/국내_내륙.csv')
# df_sea_c.to_csv('./data/국내_바다.csv')

In [77]:
df_total_c = pd.concat([df_seoul,df_gwd,df_cn,df_cb,df_jb,df_jn,df_kb,df_kn,df_jj,df_ul,df_baek])
df_total_c.drop(columns = ['평균 5cm 지중온도','평균10cm 지중온도'], inplace=True)

In [78]:
df_total_c.isnull().sum().sum()

0

In [79]:
df_total_c

,관측지점,시간,평균 기온,최저 기온,최고 기온,1시간 최다강수량,일강수량,최대 순간풍속,최대 순간 풍속 풍향,최대 풍속,...,합계 일사,일 최심신적설,일 최심적설,합계 3시간 신적설,평균 전운량,평균 중하층운량,평균 지면온도,합계 대형증발량,합계 소형증발량,안개 계속 시간
2569,서울,1980-01-01,3.8,0.5,6.6,0,0.0,6.7,20.0,4.0,...,3.23,0,0,0,8.0,-999.0,0.2,2.721902,1.8,0
2570,서울,1980-01-02,4.7,3.5,5.9,0,9.9,9.9,20.0,4.7,...,0.95,0,0,0,10.0,-999.0,1.9,2.721902,0.8,0
2571,서울,1980-01-03,3.8,-0.5,6.2,0,0,8.9,270.0,7.2,...,5.48,0,0,0,9.5,-999.0,2.8,2.721902,0.9,0
2572,서울,1980-01-04,-3.2,-6.9,-0.5,0,0,9.8,270.0,6.0,...,7.28,0,0,0,4.3,-999.0,-1.0,2.721902,1.5,0
2573,서울,1980-01-05,-5.3,-9.1,-1.0,0,0.6,6.2,230.0,5.7,...,9.21,1.2,1.2,0.0,2.5,-999.0,-2.5,2.721902,2.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175486,백령도,2021-12-28,2.0,-1.4,5.8,0,0.0,9.5,140.0,7.2,...,3.39,0.0,0.8,0.0,5.3,4.5,-2.1,1.100000,1.5,0
175487,백령도,2021-12-29,2.7,-1.7,6.5,0,0,19.8,340.0,13.3,...,6.36,0,0,0,5.3,5.3,1.3,2.000000,2.8,0
175488,백령도,2021-12-30,-0.8,-2.2,1.4,0,0.3,21.1,340.0,14.2,...,3.66,0,0,0.0,6.1,6.1,-1.2,1.800000,2.5,0
175489,백령도,2021-12-31,-3.1,-3.9,-1.5,0,0.0,20.6,340.0,13.4,...,8.83,0,0,0,4.8,4.8,-2.7,1.100000,1.6,0
175490,백령도,2022-01-01,2.1,-4.2,6.7,0,0.7,11.5,270.0,7.6,...,3.43,0,0,0,8.4,6.8,-0.6,1.200000,1.7,0

In [80]:
# df_total_c.to_csv('./data/국내기후.csv')